plugins: Add missing 'qemu/qht.h' header
When building a plugin we get:

  cc ... -c ../plugins/api.c
  In file included from ../plugins/api.c:43:
  ../plugins/plugin.h:45:16: error: field 'dyn_cb_arr_ht' has incomplete type
       struct qht dyn_cb_arr_ht;
                  ^~~~~~~~~~~~~

Since we expect all headers to be self-contained, add the missing
"qemu/qht.h" to avoid other developers to hit the same problem.

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20210524165226.3785324-1-f4bug@amsat.org>