target/arm/hvf: Fix build failure due to missing cpregs.h header file
cpregs.h was previously split out from cpu.h into a separate file, but
I think this was forgotten to be included in hvf.c. I got a build failure
when trying to build on Apple Silicon:

[...]

../target/arm/hvf/hvf.c:591:33: error: use of undeclared identifier 'ARM_CP_NO_RAW'
            assert(!(ri->type & ARM_CP_NO_RAW));

Signed-off-by: Stephen Michael Jothen <sjothen@gmail.com>
Message-Id: <Yo5Lv4Hu4jrBbGCi@air-old.local>