usb/host-libusb: Check for USBDEVFS_GET_SPEED ioctl support
Fixes compilation issue with older kernels, below is the error which is
fixed.

hw/usb/host-libusb.c:954:32: error: ‘USBDEVFS_GET_SPEED’ undeclared
(first use in this function)
         int rc = ioctl(hostfd, USBDEVFS_GET_SPEED, NULL);

Signed-off-by: Sai Pavan Boddu <sai.pavan.boddu@xilinx.com>
Message-Id: <1599049003-2937-1-git-send-email-sai.pavan.boddu@xilinx.com>