usb-mtp: Fix build with gcc 9
Build fails with gcc 9:

  CC      hw/usb/dev-mtp.o
hw/usb/dev-mtp.c: In function ‘usb_mtp_write_metadata’:
hw/usb/dev-mtp.c:1754:36: error: taking address of packed member of ‘struct <anonymous>’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1754 |                             dataset->filename);
      |                             ~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors

The way the MTP protocol encodes strings with a leading 8-bit unsigned
integer containing the string length causes the @filename field of the
packed ObjectInfo structure to be unaligned.

Use a temporary buffer for the utf16 filename instead of passing the
dataset->filename pointer around.

Signed-off-by: Greg Kurz <groug@kaod.org>
Message-Id: <155137665241.44413.528147250140332507.stgit@bahia.lan>