hw/i386: The i440fx is not a machine, remove it from the machine list
When building with CONFIG_ISAPC=n and CONFIG_I440FX=y we get:

  $ make subdir-x86_64-softmmu
  [...]
  /usr/bin/ld: hw/i386/pc_piix.o: in function `pc_init1':
  /source/qemu/hw/i386/pc_piix.c:261: undefined reference to `isa_ide_init'
  /usr/bin/ld: /source/qemu/hw/i386/pc_piix.c:261: undefined reference to `isa_ide_init'
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:204: qemu-system-x86_64] Error 1

This is because the I440FX device is a North Bridge, not a machine.
It is however used by the ISAPC machine.

Correct the dependency in the ISAPC Kconfig.

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20190427141905.20393-1-philmd@redhat.com>