Compress lines for immediate return
Compress two lines into a single line if immediate return statement is found.

It also remove variables progress, val, data, ret and sock
as they are no longer needed.

Remove space between function "mixer_load" and '(' to fix the
checkpatch.pl error:-
ERROR: space prohibited between function name and open parenthesis '('

Signed-off-by: Simran Singhal <singhalsimran0@gmail.com>
Message-Id: <20200401121101.GA26994@simran-Inspiron-5558>
Acked-by: Dr. David Alan Gilbert <dgilbert@redhat.com>