gdbstub: attempt to split gdb into 32/64 bit targets [!WORKING PLZ HELP]
Instead of building gdb syscalls for every target only build what
really matters, 64 or 32 bit support.

[AJB: Any clues or hints, I get a double linking compilation error:

FAILED: qemu-system-aarch64
c++ -m64 -mcx16 @qemu-system-aarch64.rsp
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `use_gdb_syscalls':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:50: multiple definition of `use_gdb_syscalls'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:50: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_disable_syscalls':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:71: multiple definition of `gdb_disable_syscalls'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:71: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_syscall_reset':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:76: multiple definition of `gdb_syscall_reset'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:76: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_handled_syscall':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:81: multiple definition of `gdb_handled_syscall'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:81: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_attached':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:39: multiple definition of `gdb_do_syscallv'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:39: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_do_syscall':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:156: multiple definition of `gdb_do_syscall'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:156: first defined here
/usr/bin/ld: gdbstub/libgdb64.fa.p/syscalls.c.o: in function `gdb_handle_file_io':
/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:170: multiple definition of `gdb_handle_file_io'; gdbstub/libgdb64.fa.p/syscalls.c.o:/home/alex/lsrc/qemu.git/builds/all/../../gdbstub/syscalls.c:170: first defined here
/usr/bin/ld: /lib/x86_64-linux-gnu/libtirpc.so.3: warning: common of `rpc_createerr@@GLIBC_2.2.5' overridden by definition from /lib/x86_64-linux-gnu/libc.so.6
collect2: error: ld returned 1 exit status
]

Based-on: <20230302190846.2593720-1-alex.bennee@linaro.org>
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
Message-Id: <20230302192546.2617633-1-alex.bennee@linaro.org>