chore: rename `tricore_feature` to `is_tricore_feature_enabled`
--000000000000bcd5a405ffd4722d
Content-Type: text/plain; charset="UTF-8"

While upgrading capstone to v5
<https://github.com/Homebrew/homebrew-core/pull/135948>, there was some
name clash with the tricore_feature in capstone (which was introduced in this
PR <https://github.com/capstone-engine/capstone/pull/1973>), thus rename
tricore_feature to is_tricore_feature_enabled.

Build error log is below

/opt/homebrew/Cellar/capstone/5.0/include/capstone/tricore.h:561:3: error:
redefinition of 'tricore_feature' as different kind of symbol
} tricore_feature;
  ^
../target/tricore/cpu.h:261:19: note: previous definition is here
static inline int tricore_feature(CPUTriCoreState *env, int feature)
                  ^
1 error generated.

Let me know if that makes sense. Thanks!

<div dir="ltr">While <a href="https://github.com/Homebrew/homebrew-core/pull/135948" target="_blank">upgrading capstone to v5</a>, there was some name clash with the tricore_feature in capstone (which was introduced in <a href="https://github.com/capstone-engine/capstone/pull/1973" target="_blank">this PR</a>), thus rename tricore_feature to is_tricore_feature_enabled.<br><br>Build error log is below<br><br>/opt/homebrew/Cellar/capstone/5.0/include/capstone/tricore.h:561:3: error: redefinition of &#39;tricore_feature&#39; as different kind of symbol<br>} tricore_feature;<br>  ^<br>../target/tricore/cpu.h:261:19: note: previous definition is here<br>static inline int tricore_feature(CPUTriCoreState *env, int feature)<br>                  ^<br>1 error generated.<br><br>Let me know if that makes sense. Thanks!<br></div>

From c50272465a4eaba85afaf41e0c3340c7d3ffb894 Mon Sep 17 00:00:00 2001
From: Rui Chen <rui@chenrui.dev>
Date: Thu, 6 Jul 2023 11:13:59 -0400
Subject: [PATCH] chore: rename `tricore_feature` to
 `is_tricore_feature_enabled`

Signed-off-by: Rui Chen <rui@chenrui.dev>
Message-Id: <CA+PgxXVxVKpT0SZ3N+Fc1YvXCiwkkbqm0FmLKqLTbgcDpYCNgg@mail.gmail.com>