error: Implement the warn and free Error functions
Implement warn_report_err() and warn_reportf_err() functions which
are the same as the error_report_err() and error_reportf_err()
functions except report a warning instead of an error.

Signed-off-by: Alistair Francis <alistair.francis@xilinx.com>
Message-Id: <97215143161151f6351b4f42e2561138ba55217c.1499381754.git.alistair.francis@xilinx.com>