tests/tcg/multiarch: remove unused variable in linux-test
LLVM 15.0.0 has improved diagnostics for the
'nounused-but-set-variable' warning and now warns when
a variable is modified using pre/post increment/decrement
operators but is otherwise never read.

linux-tests.c has such an unused variable 'wcount' and since
TCG tests are compiled with -Wall -Werror, this is causing
'make check-tcg' to fail when using LLVM 15.0.0 and above:

```
qemu/tests/tcg/multiarch/linux/linux-test.c:335:9:
error: variable 'wcount' set but not used [-Werror,-Wunused-but-set-variable]
    int wcount, rcount;
        ^
1 error generated.
Makefile:119: recipe for target 'linux-test' failed
```

This patch simply removes the 'wcount' variable as it
doesn't appear to impact the semantics of the test.
The WCOUNT_MAX constant is also renamed to RCOUNT_MAX to
better reflect the usage.
Message-Id: <20221215095820.13374-1-quic_mthiyaga@quicinc.com>