pythondeps: Split sphinx_rtd_theme into its own group
Currently we have "sphinx" and "sphinx_rtd_theme" in a single
group in pythondeps.toml. This means that mkvenv will try to
install them both at once, which doesn't work if sphinx_rtd_theme
depends on a version of Sphinx which is newer than the system
one, even if the "sphinx" we're installing at the same time
would satisfy that dependency. For instance this:

 sphinx = { accepted = ">=8.0.0rc1", installed = "8.0.0rc1", canary = "sphinx-build" }
 sphinx_rtd_theme = { accepted = ">=2.1.0rc1", installed = "2.1.0rc1" }

fails like this:

mkvenv: Creating non-isolated virtual environment at 'pyvenv'
mkvenv: checking for meson>=1.1.0
mkvenv: installing meson==1.2.3
mkvenv: checking for sphinx>=8.0.0rc1
mkvenv: checking for sphinx_rtd_theme>=2.1.0rc1
mkvenv: installing sphinx==8.0.0rc1, sphinx_rtd_theme==2.1.0rc1
ERROR: Cannot install sphinx-rtd-theme==2.1.0rc1 and sphinx==8.0.0rc1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

*** Ouch! ***

Could not provide build dependency 'sphinx==8.0.0rc1':
 • Python package 'sphinx' version '4.3.2' was found, but isn't suitable.
 • A suitable version could not be obtained from PyPI.

(where 4.3.2 is the system version of sphinx on my system).

Avoid this problem by splitting sphinx_rtd_theme into its own
group in pythondeps, so we can install the new sphinx into the
venv first and the sphinx_rtd_theme afterwards.

Signed-off-by: Peter Maydell <peter.maydell@linaro.org>
Message-Id: <20240729122553.2501133-1-peter.maydell@linaro.org>