qapi: Incorrect attempt to fix building with MC146818RTC=n
When configured with --without-default-devices and setting
MC146818RTC=n, the build fails:

    LINK    x86_64-softmmu/qemu-system-x86_64
  /usr/bin/ld: qapi/qapi-commands-misc-target.o: in function `qmp_marshal_rtc_reset_reinjection':
  qapi/qapi-commands-misc-target.c:46: undefined reference to `qmp_rtc_reset_reinjection'
  /usr/bin/ld: qapi/qapi-commands-misc-target.c:46: undefined reference to `qmp_rtc_reset_reinjection'
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:206: qemu-system-x86_64] Error 1
  make: *** [Makefile:483: x86_64-softmmu/all] Error 2

This patch tries to fix this, but this is incorrect because QAPI
scripts only provide TARGET definitions, so with MC146818RTC=y we
get:

  hw/rtc/mc146818rtc.c:113:6: error: no previous prototype for ‘qmp_rtc_reset_reinjection’ [-Werror=missing-prototypes]
    113 | void qmp_rtc_reset_reinjection(Error **errp)
        |      ^~~~~~~~~~~~~~~~~~~~~~~~~
  cc1: all warnings being treated as errors
  make[1]: *** [rules.mak:69: hw/rtc/mc146818rtc.o] Error 1

Any idea? :)

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20191231184916.10235-1-philmd@redhat.com>