bsd-user: space required after semicolon
This patch fixes error style problems found by checkpatch.pl:
ERROR: space required after that ';'

Signed-off-by: Liyang Shi <shiliyang@huawei.com>

Message-Id: <339c2da9-065e-d535-b63e-b35478b050c6@huawei.com>