tests/acceptance/virtio_seg_max_adjust: Restrict to X86 architecture
Running on mainstream KVM architectures, we get:

- Aarch64

  Timeout.

  job.log:
  -------
  No machine specified, and there is no default
  Use -machine help to list supported machines

- MIPS:

   (1/1) VirtioMaxSegSettingsCheck.test_machine_types: ERROR: argument of type 'NoneType' is not iterable (0.14 s)

  job.log:
  -------
  Could not load MIPS bios 'mipsel_bios.bin', and no -kernel argument was specified

- PowerPC

   (1/1) VirtioMaxSegSettingsCheck.test_machine_types: ERROR: invalid literal for int() with base 10: 'sxxm' (0.16 s)

  job.log:
  -------
  >>> {'execute': 'query-machines'}
  <<< {'return': [{'hotpluggable-cpus': True, 'name': 'pseries-2.12-sxxm', 'numa-mem-supported': True, 'default-cpu-type': 'power8_v2.0-powerpc64-cpu', 'cpu-max': 1024, 'deprecated': False}, ...

- S390X:

   (1/1) VirtioMaxSegSettingsCheck.test_machine_types: ERROR: invalid literal for int() with base 10: 'virtio' (0.14 s)

  job.log:
  -------
  Traceback (most recent call last):
    File "virtio_seg_max_adjust.py", line 139, in test_machine_types
      if self.seg_max_adjust_enabled(m):
    File "virtio_seg_max_adjust.py", line 113, in seg_max_adjust_enabled
      major = int(ver[0])
  ValueError: invalid literal for int() with base 10: 'virtio'
  >>> {'execute': 'query-machines'}
  <<< {'return': [{'hotpluggable-cpus': True, 'name': 's390-ccw-virtio-4.0', 'numa-mem-supported': False, 'default-cpu-type': 'qemu-s390x-cpu', 'cpu-max': 248, 'deprecated': False}, ...

Assuming this test is only expected to run on the X86 architecture,
restrict the test to this particular architecture.

When this test is run on other architecture, the tests will be skipped.

Examples:

- running on S390X:

 (1/1) tests/acceptance/virtio_seg_max_adjust.py:VirtioMaxSegSettingsCheck.test_machine_types: SKIP: Architecture 's390' unsupported

- running on Aarch64 setting the QEMU binary path:

  $ uname -m && avocado --show=app run -p qemu_bin=x86_64-softmmu/qemu-system-x86_64 tests/acceptance/virtio_seg_max_adjust.py
  aarch64
  JOB ID     : 92b7fae8868920aada0cb143f9571dffdf60931d
  JOB LOG    : job-results/job-2020-01-22T17.54-92b7fae/job.log
   (1/1) tests/acceptance/virtio_seg_max_adjust.py:VirtioMaxSegSettingsCheck.test_machine_types: PASS (25.99 s)
  RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
  JOB TIME   : 26.13 s

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20200122223247.30419-6-philmd@redhat.com>