block/blkio: fix error return value on getlength()
Negative values should be return for errors.

It also helps with GCC false-positives:
../block/blkio.c: In function ‘blkio_co_getlength’:
../block/blkio.c:943:8: error: ‘ret’ may be used uninitialized [-Werror=maybe-uninitialized]
  943 |     if (ret < 0) {
      |        ^

Fixes: fd66dbd424 ("blkio: add libblkio block driver")
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
Message-Id: <20260725-fix2-v1-2-5c9a6ce7b96a@redhat.com>