hw/mips/gt64xxx_pci: Fix 'braces' coding style issues
Since we'll move this code around, fix its style first:

  ERROR: braces {} are necessary for all arms of this statement

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20190624222844.26584-4-f4bug@amsat.org>
Based-on: 20190624220056.25861-1-f4bug@amsat.org