hw/acpi: Build IPMI stubs when ACPI is disabled
When ACPI is disabled, no ACPI code depends on IPMI,
so we don't need the stubs.

We need them when IPMI is enabled and ACPI disabled,
otherwise when using '--without-default-devices' we
get:

  Undefined symbols for architecture arm64:
    "_build_ipmi_dev_aml", referenced from:
        _isa_ipmi_bt_class_init in hw_ipmi_isa_ipmi_bt.c.o
  ld: symbol(s) not found for architecture arm64

Split the source set list to avoid a too long line.

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20250526112346.48744-2-philmd@linaro.org>