linux-user: fix build with musl on aarch64
Use the standard uint64_t instead of internal __u64.

This fixes compiler error with musl libc on aarch64:
.../qemu-2.7.0/linux-user/host/aarch64/hostdep.h:28:5:
error: unknown type name '__u64'
     __u64 *pcreg = &uc->uc_mcontext.pc;
     ^~~~~

Signed-off-by: Natanael Copa <ncopa@alpinelinux.org>
Message-Id: <20161215110459.27985-1-ncopa@alpinelinux.org>