qapi/util: Include missing 'qapi/error.h' header
qapi_enum_parse() uses the Error type which is
declared in "qapi/error.h". Include "qapi/error.h"
in order to avoid:

  include/qapi/util.h:27:30: error: unknown type name 'Error'
                    int def, Error **errp);
                             ^

Note we include it after the QEnumLookup declaration
to avoid:

  In file included from include/qapi/error.h:275:
  qapi/qapi-types-error.h:30:14: error: unknown type name 'QEnumLookup'
  extern const QEnumLookup QapiErrorClass_lookup;
               ^

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20240806124138.90636-1-philmd@linaro.org>