softfloat: rename canonicalize to sf_canonicalize
On Tue, Mar 27, 2018 at 12:06:58 +0200, Bastian Koppelmann wrote:
> On 03/27/2018 11:56 AM, Bastian Koppelmann wrote:
> > When I try to build your tree with gcc version 7.3.1 20180312 (GCC), I get:
> >
> >   CC      tricore-softmmu/fpu/softfloat.o
> > /home/kbastian/coding/upstream-qemu/qemu-fpu/fpu/softfloat.c:417:19:
> > error: conflicting types for ‘canonicalize’
> >  static FloatParts canonicalize(FloatParts part, const FloatFmt *parm,
> >                    ^~~~~~~~~~~~
> > In file included from /usr/include/features.h:423:0,
> >                  from /usr/include/bits/libc-header-start.h:33,
> >                  from /usr/include/math.h:27,
> >                  from
> > /home/kbastian/coding/upstream-qemu/qemu-fpu/fpu/softfloat.c:85:
> > /usr/include/bits/mathcalls.h:385:1: note: previous declaration of
> > ‘canonicalize’ was here
> >  __MATHDECL_1 (int, canonicalize,, (_Mdouble_ *__cx, const _Mdouble_ *__x));
> >
>
> git bisect points to fb1514a0104df6740e4a60c1b08b5daf173f9737
>
> Author: Emilio G. Cota <cota@braap.org>
> Date:   Sat Mar 17 02:13:59 2018 -0400
>
>     fpu: introduce hardfloat

Thanks for pointing this out.

Turns our glibc >= 2.25 defines canonicalize(), so when including math.h
we clash with theirs.

> commit eaf5ad0bc4a67bf40999e22db6f583ebc3a806ba
> Author: Joseph Myers <joseph@codesourcery.com>
> Date:   Wed Oct 26 23:14:31 2016 +0000
>
>     Add canonicalize, canonicalizef, canonicalizel.
>
>     TS 18661-1 defines canonicalize functions to produce a canonical
>     version of a floating-point representation.  This patch implements
>     these functions for glibc.

In v3 I'll rename our canonicalize() to sf_canonicalize(); patch
appended (you can apply this message as a patch with git am --scissors).
The patch should go before the one that includes math.h, i.e.
"fpu: introduce hardfloat".

Thanks,

		Emilio

Message-Id: <20180327170522.GA2693@flamenco>