update-linux-headers.sh: add typelimits.h to portable header list
Linux kernel introduced a new UAPI header file typelimits.h in the 7.1
development cycle (commit merged in Jan 2026). This file is required by
ethtool.h and other headers that include it.

Since QEMU's update script only copies headers explicitly listed in the
for loop, typelimits.h was missing after updating to newer kernel
versions, causing compilation errors like:

  fatal error: standard-headers/linux/typelimits.h: No such file or directory

Add typelimits.h to the list of headers processed by cp_portable() to
ensure it is properly copied and sanitized into the QEMU source tree

Cc: clg@redhat.com
Cc: pbonzini@redhat.com
Cc: cohuck@redhat.com
Cc: thuth@redhat.com
Cc: mst@redhat.com
Cc: peter.maydell@linaro.org
Cc: richard.henderson@linaro.org
Cc: philmd@linaro.org
Signed-off-by: Song Gao <gaosong@loongson.cn>
Reviewed-by: Thomas Huth <thuth@redhat.com>
Message-Id: <20260427070029.1059386-2-gaosong@loongson.cn>