stubs: Add missing ACPI symbols
When building with ACPI disabled, we get:

  /usr/bin/ld: hw/i386/pc.o: in function `bochs_bios_init':
  /source/qemu/hw/i386/pc.c:1017: undefined reference to `acpi_tables_len'
  /usr/bin/ld: /source/qemu/hw/i386/pc.c:1017: undefined reference to `acpi_tables'
  collect2: error: ld returned 1 exit status
  make[1]: *** [Makefile:204: qemu-system-x86_64] Error 1

These symbols are indeed declared as extern in "hw/acpi/acpi.h".
Add them as stub to satisfy the linker.

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20190428064731.29913-6-philmd@redhat.com>