stubs: Fix notify-event stub linkage error on MinGW
In commit e4d6d41ce2 we reduced the user-mode object list,
but forgot to also change the notify.o stub in the next commit
dc70f80fb2. This triggers a linker error while compiling the
tests under MinGW:

  LINK    tests/test-timed-average.exe
 libqemuutil.a(main-loop.o): In function `qemu_notify_event':
 util/main-loop.c:139: multiple definition of `qemu_notify_event'
 tests/test-timed-average.o:/builds/huth/qemu/tests/../stubs/notify-event.c:5: first defined here
 collect2: error: ld returned 1 exit status
 rules.mak:124: recipe for target 'tests/test-timed-average.exe' failed

Correct by placing the stub object between the system emulation /
tools guards.

Fixes: dc70f80fb2 ("stubs/Makefile: Reduce the user-mode object list")
Reported-by: Thomas Huth <thuth@redhat.com>
Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20200804182241.31805-1-philmd@redhat.com>