hw/display: Declare build_vga_aml() out of "vga_int.h"
Commit cfead31326 declared build_vga_aml() in "vga_int.h".
This header happens to include various other things, such
(indirectly) pixman headers.

The freshly introduced acpi-vga.c includes "vga_int.h" to
get build_vga_aml() declaration, but ends including the
'various other things' triggering this build failure (QEMU
configured as '--enable-modules --disable-spice'):

  In file included from /home/fred/qemu-git/src/qemu/include/ui/console.h:4,
                 from ../hw/display/vga_int.h:30,
                 from ../hw/display/acpi-vga.c:4:
  include/ui/qemu-pixman.h:12:10: fatal error: pixman.h: No such file or directory
     12 | #include <pixman.h>
        |          ^~~~~~~~~~

Resolve by declaring build_vga_aml() in a ACPI/VGA specific
header named "acpi-vga.h". Adjust MAINTAINERS to avoid
checkpatch warnings.

Reported-by: Miroslav Rezanina <mrezanin@redhat.com>
Reported-by: Frederic Bezies <fredbezies@gmail.com>
Reported-by: Laurent Vivier <lvivier@redhat.com>
Resolves: https://gitlab.com/qemu-project/qemu/-/issues/1308
Fixes: cfead31326 ("AcpiDevAmlIf interface to build VGA device descs")
Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20221109222312.29347-1-philmd@linaro.org>