vl: Use qemu_strtoi() instead of strtol()
Since we'll move this code around, fix this checkpatch warning
first:

  ERROR: consider using qemu_strtol in preference to strtol

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20190712133928.21394-6-philmd@redhat.com>
Reviewed-by: Richard Henderson <richard.henderson@linaro.org>