vl: Fix 'braces' coding style issues
Since we'll move this code around, fix its style first:

  ERROR: braces {} are necessary for all arms of this statement style

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20190712133928.21394-5-philmd@redhat.com>
Reviewed-by: Richard Henderson <richard.henderson@linaro.org>