9pfs: fix missing sys/mount.h include
Fixes the following build error:

  fsdev/file-op-9p.h:156:56: error: declaration of 'struct statfs' will
  not be visible outside of this function [-Werror,-Wvisibility]
    int (*statfs)(FsContext *s, V9fsPath *path, struct statfs *stbuf);
                                                       ^

As Windows neither has statfs, nor sys/mount.h, don't include it there.

Fixes: 684f91203439 ("tests/9p: split virtio-9p-test.c ...")
Link: https://lore.kernel.org/all/2690108.PsDodiG1Zx@silver/
Signed-off-by: Christian Schoenebeck <qemu_oss@crudebyte.com>
Reviewed-by: Bin Meng <bmeng.cn@gmail.com>
Message-Id: <E1ooNWu-0002oC-76@lizzy.crudebyte.com>