.travis.yml: Temporarily disable the aarch64 job
Travis-CI Aarch64 runners are currently broken, the build fails
because the filesystem quota is full [1]:

    AR      libqemuutil.a
  nm: qemu-sockets.o: Bad value
    LINK    qemu-ga
  qga/main.o: In function `main':
  /home/travis/build/qemu/qemu/qga/main.c:1494: undefined reference to `socket_local_address'
  qga/channel-posix.o: In function `ga_channel_open':
  /home/travis/build/qemu/qemu/qga/channel-posix.c:210: undefined reference to `socket_parse'
  /home/travis/build/qemu/qemu/qga/channel-posix.c:193: undefined reference to `unix_listen'
  /home/travis/build/qemu/qemu/qga/channel-posix.c:218: undefined reference to `socket_listen'
  collect2: error: ld returned 1 exit status
  Makefile:686: recipe for target 'qemu-ga' failed
  make: *** [qemu-ga] Error 1

Per [2], LXD container have 'approx 18GB' of storage, but our runner show:

  $ df -h
  Filesystem                                                                                         Size  Used Avail Use% Mounted on
  /var/snap/lxd/common/lxd/storage-pools/instances/containers/travis-job-qemu-qemu-693775643/rootfs  895G   38G  854G   5% /

As we suppose a filesystem quota makes our build fail,
disable the aarch64 job as a temporary kludge.

[1] https://travis-ci.org/github/qemu/qemu/jobs/693775643
[2] https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20200602113702.28549-1-f4bug@amsat.org>