gitlab: Escape git-describe match pattern on Windows hosts
Properly escape git-describe 'match' pattern to avoid (MinGW):

  $ if grep -q "EXESUF=.exe" config-host.mak; then make installer;
    version="$(git describe --match v[0-9]*)";
    mv -v qemu-setup*.exe qemu-setup-${version}.exe; fi
  fatal: No names found, cannot describe anything.
  ERROR: Job failed: exit code 1

Reported-by: Cédric Le Goater <clg@kaod.org>
Fixes: 8619b5ddb56 ("ci: build & store windows installer")
Resolves: https://gitlab.com/qemu-project/qemu/-/issues/591
Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20210901145229.4132606-1-philmd@redhat.com>