configure: Improve error message with specified meson path is not found
When building on a system where meson isn't available,
but installed manually as user pip package, we get:

  $ ../configure --meson=~/.local/bin/meson
  qemu/configure: line 6387: --version: command not found
  You are attempting to run "setup" which requires administrative
  privileges, but more information is needed in order to do so.
  Authenticating as "root"
  Password:

Improve the error message to something less scary:

  $ ../configure --meson=~/.local/bin/meson
  ERROR: Meson not found.  Use --meson=/path/to/meson (absolute path)

Actually in this case the fix is to use $HOME, not unexpanded ~:

  $ ../configure --meson=$HOME/.local/bin/meson
  The Meson build system
  Version: 0.56.99
  ...

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20210416102559.213649-1-philmd@redhat.com>
Reviewed-by: Darren Kenny <darren.kenny@oracle.com>