tcg: Fix tci build
The previous commit 659ef5cbb8 enable LDST_LABELS in tci target,
but which causes tci build error like:
tcg/tcg.c:116:13: error: ‘tcg_out_ldst_finalize’ used but never defined [-Werror]
 static bool tcg_out_ldst_finalize(TCGContext *s);
             ^
cc1: all warnings being treated as errors
make[1]: *** [tcg/tcg.o] Error 1
make: *** [subdir-x86_64-softmmu] Error 2

If this macro is not used in tci, we could just delete it.

Signed-off-by: Jincheng Miao <jincheng.miao@gmail.com>
Message-Id: <1505175459-27177-1-git-send-email-jincheng.miao@gmail.com>