vhost-user-bridge: fix "unknown type name" compilation error
osdep.h should be included first:

  CC      tests/vhost-user-bridge.o
In file included from /home/elmarco/src/qemu/tests/vhost-user-bridge.c:32:
/home/elmarco/src/qemu/include/qemu/atomic.h:480:1: error: unknown type name ‘int64_t’
 int64_t  atomic_read_i64(const int64_t *ptr);
 ^~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:480:32: error: unknown type name ‘int64_t’
 int64_t  atomic_read_i64(const int64_t *ptr);
                                ^~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:481:1: error: unknown type name ‘uint64_t’
 uint64_t atomic_read_u64(const uint64_t *ptr);
 ^~~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:481:32: error: unknown type name ‘uint64_t’
 uint64_t atomic_read_u64(const uint64_t *ptr);
                                ^~~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:482:21: error: unknown type name ‘int64_t’
 void atomic_set_i64(int64_t *ptr, int64_t val);
                     ^~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:482:35: error: unknown type name ‘int64_t’
 void atomic_set_i64(int64_t *ptr, int64_t val);
                                   ^~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:483:21: error: unknown type name ‘uint64_t’
 void atomic_set_u64(uint64_t *ptr, uint64_t val);
                     ^~~~~~~~
/home/elmarco/src/qemu/include/qemu/atomic.h:483:36: error: unknown type name ‘uint64_t’
 void atomic_set_u64(uint64_t *ptr, uint64_t val);
                                    ^~~~~~~~

(regression from 782da5b2921c4d18777d5d5bd9385b9f7beae360)

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
Message-Id: <20181031104136.9953-1-marcandre.lureau@redhat.com>
Reviewed-by: Michal Privoznik <mprivozn@redhat.com>
Reviewed-by: Emilio G. Cota <cota@braap.org>
Signed-off-by: Paolo Bonzini <pbonzini@redhat.com>
Message-Id: <20181219151917.3874-3-pbonzini@redhat.com>