Fix duplicate symbol error on MacOS build
The issue started after commit https://github.com/qemu/qemu/commit/59f4d65584bd3372070e2484876436c8d02505e4

Reproduction:
  1. In the build directory on MacOS (haven't tried on other OS), run:
       ../configure --enable-rust --target-list=aarch64-softmmu
  2. Then run either:
       ninja -C .
       OR
       make
  3. At the end, you will encounter the error:
       duplicate symbol '_pl011_create' in:
           /Users/tanishdesai37/Downloads/qemu-master/build/libcommon.a.p/hw_char_pl011.c.o
           librust_aarch64_softmmu.a[5](pl011.pl011.390d424367e209af-cgu.1.rcgu.o)
       ld: 1 duplicate symbols

Root cause:
  Both CONFIG_PL011 and X_PL011_RUST are selected, causing C++ and Rust to produce the same object.
  This is due to the commit above where 'select PL011' forces a true condition instead of checking if HAVE_RUST is true.
  If HAVE_RUST is true, X_PL011_RUST should be selected instead of CONFIG_PL011.

Signed-off-by: Tanish Desai <tanishdesai37@gmail.com>
Message-Id: <20250319023036.71493-1-tanishdesai37@gmail.com>