hw/acpi: fix breakage due to missing aml stub definitions when acpi is off
Some HW architectures do not support acpi and CONFIG_ACPI is off for them. For
those architectures, dummy stub function definitions help to resolve symbols.
This change adds couple of dummy stub definitions so that symbols for those can
be resolved and failures such as the following can be fixed for or1k targets.

Configuration:
qemu/build $ ../configure --enable-werror --disable-docs --disable-nettle
             --enable-gcrypt --enable-fdt=system --enable-modules
             --enable-trace-backends=dtrace --enable-docs
	     --enable-vfio-user-server
             --target-list="ppc64-softmmu or1k-softmmu s390x-softmmu
               x86_64-softmmu rx-softmmu sh4-softmmu nios2-softmmu"

actual failure:

qemu/build $ QTEST_QEMU_BINARY=./qemu-system-or1k  ./tests/qtest/qos-test
failed to open module:
/build/qemu/qemu/build/qemu-bundle/usr/local/lib64/qemu/hw-display-virtio-vga.so:
undefined symbol: aml_return
qemu-system-or1k: ../util/error.c:59: error_setv: Assertion `*errp ==
NULL' failed.
Broken pipe
../tests/qtest/libqtest.c:188: kill_qemu() detected QEMU death from
signal 6 (Aborted) (core dumped)
Aborted (core dumped)

Signed-off-by: Ani Sinha <ani@anisinha.ca>
Message-Id: <20221107133920.865060-1-ani@anisinha.ca>