intc/i8259: avoid (false positive) gcc warning
some copiler versions are smart enough to detect a potentially
uninitialized variable, but are not smart enough to detect that this
cannot happen due to the code flow:

../hw/intc/i8259.c: In function ‘pic_read_irq’:
../hw/intc/i8259.c:203:13: error: ‘irq2’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   203 |         irq = irq2 + 8;
       |         ~~~~^~~~~~~~~~

Let us initialize irq2 to -1 to avoid this warning as the most simple
solution.

Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>
Message-Id: <20210318154738.27094-1-borntraeger@de.ibm.com>