target/s390x: tcg stubs
missing since 55c3ceef61:

    LINK    s390x-softmmu/qemu-system-s390x
  target/s390x/cpu.o: In function `s390_cpu_class_init':
  target/s390x/cpu.c:500: undefined reference to `s390x_translate_init'

Suggested-by: Eduardo Habkost <ehabkost@redhat.com>
Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20171030030553.21259-4-f4bug@amsat.org>