tests/docker: fix ccache directory variable expansion
DOCKER_QEMU_CCACHE_DIR is missing $() around DOCKER_QEMU_CACHE_DIR, so
$HOME/.cache/qemu is never created.  podman then fails to mount it:

  Error: statfs /home/user/.cache/qemu: no such file or directory

It only works if the directory already exists.  Add the missing $().

Fixes: 8a1975e4d44b ("tests/docker: expose $HOME/.cache/qemu as docker volume")
Signed-off-by: Anders Roxell <anders.roxell@linaro.org>
Message-Id: <20260915072403.347639-1-anders.roxell@linaro.org>