audio/audio: Add missing fall through comment
GCC9 is confused by this comment when building with
CFLAG -Wimplicit-fallthrough=2:

  audio/audio.c: In function ‘audio_pcm_init_info’:
  audio/audio.c:306:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
    306 |         sign = 1;
        |         ~~~~~^~~
  audio/audio.c:307:5: note: here
    307 |     case AUDIO_FORMAT_U8:
        |     ^~~~
  cc1: all warnings being treated as errors

Add the missing fall through comment, similarly to e46349414.

Fixes: 2b9cce8c8c
Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20191217173425.5082-2-philmd@redhat.com>