tests/tcg/hexagon/overflow.c: add missing include
../tests/tcg/hexagon/overflow.c:59:1: error: unknown type name 'bool'

Signed-off-by: Pierrick Bouvier <pierrick.bouvier@oss.qualcomm.com>
Message-Id: <20260706223343.988769-44-pierrick.bouvier@oss.qualcomm.com>