tests/tcg/multiarch: Define _LARGEFILE64_SOURCE
With newer clang builds (19.x), there's a warning for implicit function
declarations and it rejects linux-test.c.

glibc/musl's readdir64() declaration in dirent is guarded by
_LARGEFILE64_SOURCE, so we'll define it to fix the warning.

      BUILD   hexagon-linux-user guest-tests
    /local/mnt/workspace/upstream/toolchain_for_hexagon/qemu/tests/tcg/multiarch/linux/linux-test.c:189:14: error: call to undeclared function 'readdir64'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      189 |         de = readdir64(dir);
          |              ^

Signed-off-by: Brian Cain <bcain@quicinc.com>
Message-Id: <20240907023924.1394728-1-bcain@quicinc.com>