accel/tcg: add a stub for tcg_region_init()
missing since e8feb96fcc:

    LINK    x86_64-softmmu/qemu-system-x86_64
  cpus.o: In function `qemu_tcg_init_vcpu':
  cpus.c:1677: undefined reference to `tcg_region_init'

Suggested-by: Eduardo Habkost <ehabkost@redhat.com>
Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20171030030553.21259-5-f4bug@amsat.org>