error: add error_get_hint
Add a function to export error hint - a pair to error_get_pretty. It's
needed to handle errors by hand, where we can't just report it or
propagate.

Signed-off-by: Vladimir Sementsov-Ogievskiy <vsementsov@virtuozzo.com>
Message-Id: <20181102151152.288399-2-vsementsov@virtuozzo.com>
Reviewed-by: Eric Blake <eblake@redhat.com>