monitor: vnc: Fix compilation error if CONFIG_VNC is disable
How to reproduce it?
===

```
$ ./configure --disable-spice --disable-vte --disable-vnc \
    --disable-vnc-jpeg --disable-vnc-png --disable-vnc-sasl
$ make
...
monitor/hmp-cmds.c: In function ‘hmp_change’:
monitor/hmp-cmds.c:1985:17: error: unused variable ‘hmp_mon’
     [-Werror=unused-variable]
     MonitorHMP *hmp_mon = container_of(mon, MonitorHMP, common);
```

Fix
===

Move `hmp_mon` variable within the `CONFIG_VNC` block

Signed-off-by: Julio Montes <julio.montes@intel.com>
Message-Id: <20190702190131.5780-1-julio.montes@intel.com>