log: Fix result of strstr to 'const char *'
Assigning the result of strstr() to a 'char *' is unsafe since
strstr() returns a pointer into the original string which is a
read-only 'const char *' string.

A recent change in glibc 2.42.9000  :

   https://sourceware.org/git/?p=glibc.git;a=commit;h=cd748a63ab1a7ae846175c532a3daab341c62690

breaks compiles, complaining the result of strstr() is not a
'const char *' :

../util/log.c:208:24: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  208 |         char *pidstr = strstr(filename, "%");
      |                        ^~~~~~

Fix that.

Reviewed-by: Laurent Vivier <laurent@vivier.eu>
Reviewed-by: Peter Maydell <peter.maydell@linaro.org>
Link: https://lore.kernel.org/qemu-devel/20251209150346.650473-1-clg@redhat.com
Signed-off-by: Cédric Le Goater <clg@redhat.com>
Message-Id: <20251209154128.661390-1-clg@redhat.com>