gitlab-ci: Add a job to cover the --without-default-devices config
We test './configure --without-default-devices' since commit
20885b5b169 (".travis.yml: test that no-default-device builds
do not regress") in Travis-CI.

As we prefer to use GitLab-CI, add the equivalent job there.

One minor difference: the GitLab Ubuntu docker image has the
Xen devel packages installed. As it is automatically selected,
we need to disable it with the --disable-xen option, else the
build fails:

  /usr/bin/ld: libcommon.fa.p/hw_xen_xen-legacy-backend.c.o: in function `xen_be_register_common':
  hw/xen/xen-legacy-backend.c:754: undefined reference to `xen_9pfs_ops'
  /usr/bin/ld: libcommon.fa.p/fsdev_qemu-fsdev.c.o:(.data.rel+0x8): undefined reference to `local_ops'
  /usr/bin/ld: libcommon.fa.p/fsdev_qemu-fsdev.c.o:(.data.rel+0x20): undefined reference to `synth_ops'
  /usr/bin/ld: libcommon.fa.p/fsdev_qemu-fsdev.c.o:(.data.rel+0x38): undefined reference to `proxy_ops'
  collect2: error: ld returned 1 exit status

Signed-off-by: Philippe Mathieu-Daudé <philmd@redhat.com>
Message-Id: <20201103164604.2692357-3-philmd@redhat.com>