tests: Fix broken tcg test compilation
The first build error to be seen is that linux-test.c fails to
include cutils.h:

linux-test.c:42:25: fatal error: qemu/cutils.h: No such file or directory

This is because toplevel include/ dir is not put onto compiler's
command line. After that:

qemu.git/include/qemu/cutils.h:171:1: error: unknown type name ‘bool’

So we need to include "qemu/osdep.h" which will define bool type
for us. However, osdep.h eventually includes glib.h from system,
therefore we need to put GLIB_CFLAGS onto compiler's command line
too.

Lastly, getrusage is used in linux-test.c. This function and a
struct it uses are defined in sys/resource.h:

linux-test.c:247:5: warning: implicit declaration of function ‘getrusage’

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>
Message-Id: <16b62ea67fcc34be255541423fbb1db9cdc1c258.1472720373.git.mprivozn@redhat.com>