ui: Link dbus-display with pixman again
Since its introduction in commit 142ca628a7 ("ui: add a D-Bus
display backend"), dbus_display1 depends on pixman.
Unfortunatly the refactor commit 1222070e77 ("meson: ensure
dbus-display generated code is built before other units")
dropped that dependency. Recently commit 6cc5a6159a ("ui/dbus:
win32 support") expose this problem:

  In file included from include/ui/console.h:4,
                   from ui/dbus.h:31,
                   from ../audio/dbusaudio.c:36:
  include/ui/qemu-pixman.h:12:10: fatal error: pixman.h: No such file or directory
     12 | #include <pixman.h>
        |          ^~~~~~~~~~

Restore the missing dependency on pixman.

Reported-by: Frederic Bezies <fredbezies@gmail.com>
Resolves: https://gitlab.com/qemu-project/qemu/-/issues/1739
Fixes: 1222070e77 ("meson: ensure dbus-display generated code is built before other units")
Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20230630234839.14716-1-philmd@linaro.org>