.travis.yml: force a brew update for MacOS builds
It looks like the Travis image package databases are out of date
causing the build to error with:

  Error: Your Homebrew is outdated. Please run `brew update`.
  Error: Kernel.exit

Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
Message-Id: <20190619194021.8240-18-alex.bennee@linaro.org>