hw/hyperv: Fix 32-bit build error for vmbus.
../qemu/hw/hyperv/vmbus.c: In function ‘gpadl_iter_io’:
../qemu/hw/hyperv/vmbus.c:383:13: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
  383 |         p = (void *)(((uintptr_t)iter->map & TARGET_PAGE_MASK) | off_in_page);
      |             ^
cc1: all warnings being treated as errors

Fixes: 0d71f7082d7 ("vmbus: vmbus implementation")
Signed-off-by: Richard Henderson <richard.henderson@linaro.org>
Message-Id: <20200906050113.2783642-1-richard.henderson@linaro.org>