linux-user: Add missing includes
We're getting errors about this:
linux-user/elfload.c:2770:36: error: use of undeclared identifier 'MAP_FIXED_NOREPLACE'

Signed-off-by: Peter Foley <pefoley@google.com>
Message-Id: <20250904-includes-v1-1-a04a0ea14fd1@google.com>