target/sparc: Fix string format errors when DEBUG_MMU is defined
Fix when building with DEBUG_MMU:

  target/sparc/ldst_helper.c:245:72: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                    DPRINTF_MMU("auto demap entry [%d] %lx->%lx\n", i, vaddr,
                                                       ~~~             ^~~~~
                                                       %llx
  target/sparc/ldst_helper.c:1736:60: error: no member named 'immuregs' in 'struct CPUArchState'
                              PRIx64 "\n", reg, oldreg, env->immuregs[reg]);
                                                        ~~~  ^
  target/sparc/ldst_helper.c:1820:60: error: no member named 'dmmuregs' in 'struct CPUArchState'
                              PRIx64 "\n", reg, oldreg, env->dmmuregs[reg]);
                                                        ~~~  ^

Fixes: 96df2bc99f ("target-sparc: use SparcV9MMU type for sparc64 I/D-MMUs")
Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20240321154838.95771-16-philmd@linaro.org>