helpers: build vhost-user-gpu only for softmmu
with

  ./configure --enable-user --disable-tools --disable-system

it fails with:

  /usr/bin/ld: contrib/vhost-user-gpu/main.o: in function `vg_resource_destroy':
  .../contrib/vhost-user-gpu/main.c:382: undefined reference to `pixman_image_unref'
  /usr/bin/ld: contrib/vhost-user-gpu/main.o: in function `vg_resource_flush':
  .../contrib/vhost-user-gpu/main.c:694: undefined reference to `pixman_region_init_rect'
  /usr/bin/ld: .../contrib/vhost-user-gpu/main.c:763: undefined reference to `pixman_region_fini'

Fixes: d52c454aadcd ("contrib: add vhost-user-gpu")
Cc: marcandre.lureau@redhat.com
Signed-off-by: Laurent Vivier <lvivier@redhat.com>
Message-Id: <20190614174901.20359-1-lvivier@redhat.com>
Reviewed-by: Marc-André Lureau <marcandre.lureau@redhat.com>