coroutine: Add missing <qemu/atomic.h> include
qemu_co_mutex_assert_locked() calls qatomic_read(), which
is declared in <qemu/atomic.h>. This fixes when refactoring:

  In file included from include/qemu/osdep.h:113,
                   from ../../util/error-report.c:13:
  include/qemu/coroutine.h: In function 'qemu_co_mutex_assert_locked':
  include/qemu/coroutine.h:182:12: error: implicit declaration of function 'qatomic_read' [-Werror=implicit-function-declaration]
    182 |     assert(qatomic_read(&mutex->locked) &&
        |            ^~~~~~~~~~~~

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20221125175532.48858-1-philmd@linaro.org>