hw/xen/xen_pt: fix missing include
FAILED: libqemu-i386-softmmu.a.p/hw_xen_xen_pt.c.o
...
/home/user/.work/qemu/hw/xen/xen_pt.c: In function ‘xen_pt_need_gsi’:
/home/user/.work/qemu/hw/xen/xen_pt.c:783:9: error: implicit declaration of function ‘error_report’; did you mean ‘error_report_err’? [-Wimplicit-function-declaration]
  783 |         error_report("Cannot open %s: %s", guest_type, strerror(errno));
      |         ^~~~~~~~~~~~
      |         error_report_err
/home/user/.work/qemu/hw/xen/xen_pt.c:783:9: error: nested extern declaration of ‘error_report’ [-Werror=nested-externs]
cc1: all warnings being treated as errors

Fixes: 012842c ("log: make '-msg timestamp=on' apply to all qemu_log usage")
Signed-off-by: Pierrick Bouvier <pierrick.bouvier@linaro.org>
Message-Id: <20250725165749.3893240-1-pierrick.bouvier@linaro.org>