tpm: Don't call tpm_cleanup unless CONFIG_TPM.
When compiling with --disable-tpm:

  ../vl.o: In function `main':
  /home/rjones/d/qemu/vl.c:4908: undefined reference to `tpm_cleanup'

This appears to have been introduced in commit c37cacabf228
("tpm: Move tpm_cleanup() to right place").

Signed-off-by: Richard W.M. Jones <rjones@redhat.com>
Message-Id: <20171019075031.25507-1-rjones@redhat.com>
Reviewed-by: Stefan Berger <stefanb@linux.vnet.ibm.com>