travis.yml: Fix 'Clang (main-softmmu)' job on Ubuntu Bionic
On Ubuntu Bionic environment the build with Clang's sanitizer
fails with error:

```
LINK    tests/qemu-iotests/socket_scm_helper

tests/qemu-iotests/socket_scm_helper.o: In function `send_fd':

/home/travis/build/wainersm/qemu/tests/qemu-iotests/socket_scm_helper.c:53: undefined reference to `__ubsan_handle_type_mismatch_v1'
```

In order to solve that problem it was needed to explicitly pass
'--cxx=clang++' to the configure.

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
Message-Id: <20200217201609.788825-5-wainersm@redhat.com>