accel/kvm: Add more stubs
To be able to make softmmu/cpus.c not target-specific, we need to
add two more KVM stubs, to avoid:

  /usr/bin/ld: libcommon.fa.p/softmmu_cpus.c.o: in function `cpu_thread_is_idle':
  softmmu/cpus.c:85: undefined reference to `kvm_halt_in_kernel_allowed'
  /usr/bin/ld: libcommon.fa.p/softmmu_cpus.c.o: in function `cpu_check_are_resettable':
  include/sysemu/hw_accel.h:28: undefined reference to `kvm_cpu_check_are_resettable'

Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20210517115525.1088693-2-f4bug@amsat.org>