error: Reduce unnecessary error propagation
When all we do with an Error we receive into a local variable is
propagating to somewhere else, we can just as well receive it there
right away, even when we need to keep error_propagate() for other
error paths.

Signed-off-by: Markus Armbruster <armbru@redhat.com>
Message-Id: <20200702155000.3455325-38-armbru@redhat.com>
Based-on: Message-Id: <20200702110931.2953148-1-armbru@redhat.com>