tests/migration: Restrict initrd-stress.img to Linux
Trying to build initrd-stress.img on Darwin we get:

  $ ninja tests/migration/initrd-stress.img
  Compiling C object tests/migration/stress.p/stress.c.o
  FAILED: tests/migration/stress.p/stress.c.o
  ../tests/migration/stress.c:24:10: fatal error: 'linux/random.h' file not found
  #include <linux/random.h>
           ^~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

Per the include path, this test is Linux specific.
Since this is the single binary built in this directory,
restrict the whole meson.build to Linux.

Signed-off-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20230710175607.32818-1-philmd@linaro.org>