scripts: render_block_graph: Implement proper argument parser
As no argument parsing is employed the script is hard to use and when
running without arguments it blurbs:

 $ ./scripts/render_block_graph.py
 Traceback (most recent call last):
   File "/home/pipo/git/qemu.git/./scripts/render_block_graph.py", line 135, in <module>
     obj = sys.argv[1]
          ~~~~~~~~^^^
 IndexError: list index out of range

instead of an actionable error. The user then usually needs to read the
script to understand arguments.

Implement proper argument parsing via 'argparse'. The following
arguments will be supported:

  $ ./scripts/render_block_graph.py --help
  usage: render_block_graph.py [-h] (--socket SOCKET | --vm VM) [--uri URI] [--output OUTPUT]

  Tool that renders the qemu block graph into a image.

  options:
    -h, --help       show this help message and exit
    --socket SOCKET  socket mode - path to qemu monitor socket
    --vm VM          libvirt mode - name of libvirt VM
    --uri URI        libvirt URI to connect to
    --output OUTPUT  path to output image (.png suffix added); in libvirt mode default is the name of the VM

Usage then requires one of '--vm' or '--socket'. In libvirt mode the
output file is by default populated from the VM name and the '--uri'
parameter allows overriding the libvirt connection uri.

Signed-off-by: Peter Krempa <pkrempa@redhat.com>
Message-Id: <72ba260b04c021740924e5638a7e165ed5121687.1770108741.git.pkrempa@redhat.com>