target/i386: tcg stubs
missing since 55c3ceef61:

    LINK    x86_64-softmmu/qemu-system-x86_64
  target/i386/cpu.o: In function `x86_cpu_common_class_init':
  target/i386/cpu.c:4215: undefined reference to `tcg_x86_init'

Suggested-by: Eduardo Habkost <ehabkost@redhat.com>
Signed-off-by: Philippe Mathieu-Daudé <f4bug@amsat.org>
Message-Id: <20171030030553.21259-3-f4bug@amsat.org>