qerror: QERR_DEVICE_IN_USE is no longer used, drop
Signed-off-by: Markus Armbruster <armbru@redhat.com>
Reviewed-by: Philippe Mathieu-Daudé <philmd@linaro.org>
Message-Id: <20240306131055.2460378-3-armbru@redhat.com>