hw/i386/fw_cfg.c: fix non-legacy smbios build
When building qemu with smbios but not legacy mode (eg minimal microvm build),
link fails with:

  hw/i386/fw_cfg.c:74: undefined reference to `smbios_get_table_legacy'

This is because fw_cfg interface can call this function if CONFIG_SMBIOS
is defined.  Made this code block to depend on CONFIG_SMBIOS_LEGACY.

Fixes: b42b0e4daaa5 "smbios: build legacy mode code only for 'pc' machine"
Signed-off-by: Michael Tokarev <mjt@tls.msk.ru>
Message-Id: <20240325130920.349521-1-mjt@tls.msk.ru>