qerror: Delete unused QERR_PROPERTY_VALUE_BAD macro
Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>
Message-Id: <20201030202131.796967-16-ehabkost@redhat.com>
Based-on: 20201029220246.472693-1-ehabkost@redhat.com